name: Test

on:
  pull_request:
    types: [opened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: johnsoncwb/my-whank-you-action@v1
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
